### ISSUE TITLE
Futile search employing the random option

### ISSUE THREAD

**Issue by jetrca** [onli/izulu#4]
Dear everyone,

While today, at pentecost, the holy spirit has come upon mankind, my Izulu installation is still searching for enlightment in every corner of my file system.

I run izuli with command _izulu -c dresden -d -n -p -r -t -co unity_ (in the unity autostart), thus employing the random option. Untlil recently I did not set the paths for the image folders in the config file. Afaik in this case izulu should use the default images and silently count to 3600. Instead, it used to start a find process examining my file system restlessly. As I use to mount a remote virtual hard disk via davfs2, this process used to claim almost the complete bandwidth of my internet connection, thus disturbing the functionality of other programs.

I could circumvent the problem by setting the paths to the image folders, but Onli asked me to make an issue of this, as this endless search does not fit into the supposed behavour of Izulu.

Thanks so far to Onli for his advise.

**Comment by onli** [comment]
Thanks for reporting this. The new version (0.6.4) should fix this and soon arrive in the PPA. Could you report back whether that really fixes it for you?

**Comment by onli** [comment]
Reported to work :)
