### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Sh4kE** [onli/izulu#7]
When starting izulu I only get this stacktrace:

```
izulu -c Berlin -gr -i 900 -n -p -r -rd germany -t -tg -tm 
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unable to read font `Helvetica' @ error/annotate.c/RenderFreetype/1316.
convert: unrecognized gravity type `-tm' @ error/convert.c/ConvertImageCommand/1720.
```

Im on Arch (4.4.19-1-MANJARO)

I installed ephifonts, which should include Helvetica. So I have no clue what could be the reason

**Comment by onli** [comment]
Thanks for the report. 

It seems that Helvetica is not available on your system. https://aur.archlinux.org/packages/ephifonts/ mentions some problems with the Helvetica-font, maybe that is related. Could you show me the output of `convert -list font`?

**Comment by Sh4kE** [comment]
Wow I didn't know I have so many fonts available, so I put it in pastebin instead:

http://pastebin.com/vxHdguHk

**Comment by Sh4kE** [comment]
Aha, this particular problem isn't causing the malfunctioning. I use mate as my window environment and it seems like your script cannot find out the right command for setting the background. When I enter the wpcommand manually in the config, than it seems to work as expected. 

Unfortunatly I couldn't figure out the default mate command for setting a wallpaper, I don't even know if there is one. So I installed feh, but how do I tell feh to set the background and not opening up a new window?

**Comment by Sh4kE** [comment]
Finally found out how to deal with this in mate. Maybe you want to incorporate this in your script as well:

```
gsettings set org.mate.background picture-filename
```

**Comment by onli** [comment]
Are you certain the imagemagick error message does not matter? He succeeds in writing the forecast day names and the temperature to the image anyway? If not, that should be fixable by switching to DejaVu.

> gsettings set org.mate.background picture-filename

Thanks for that. Izulu indeed did not know about mate yet. Now all that is missing is to detect that mate is running. Could you test for me whether `echo $XDG_CURRENT_DESKTOP` outputs anything?

PS:

> So I installed feh, but how do I tell feh to set the background and not opening up a new window?

Izulu made feh open a window? That should not happen. The command to set a background image is `feh --bg-scale` (or one of the other background scale ratios).

**Comment by Sh4kE** [comment]
Hmm I guess then it's not working. I don't see any information on my desktop. But I'm already happy to get random images from flickr ;) And how do I tell izulu to use Dejavu?

Anyway, the output of my env var is this: 

```
> echo $XDG_CURRENT_DESKTOP
> MATE
```

I tried feh with this option as well, but unfortunatly it did not set my background like this. Same for xsetroot when using the right options. I don't know what mate is doing in the background that this is not possible.

**Comment by onli** [comment]
> I don't know what mate is doing in the background that this is not possible.

If Mate behaves like the old gnome nautilus is taking the desktop for its own, to paint the desktop icons and the background image. 

> And how do I tell izulu to use Dejavu?

We would have to patch the file **izulu**. It is a bash script, so it is easy to do manually. There are two instances where imagemagick is called with `-font Helvetica`, both are in `setImage()`, [Line 201](https://github.com/onli/izulu/blob/5311ac922f4409b120a063ed1abfefc12ad61595/izulu#L201) and [Line 211](https://github.com/onli/izulu/blob/5311ac922f4409b120a063ed1abfefc12ad61595/izulu#L211). Please change both to `-font DejaVu-Sans-Condensed`. 

If that works for you I'll make a new bugfix release with the font change and support for mate :)

**Comment by onli** [comment]
Easier: Let's test both changes, that would be great. Here is the potential new izulu version: https://gist.github.com/onli/7d4fe397ab004075890c7ebc40af7563. Could you test that file? It should work from everywhere, just start in in the terminal with the params you used before, -p and -t especially

**Comment by Sh4kE** [comment]
It seems like this command:

```
gsettings set org.mate.desktop.background picture-options "stretched"
```

is not working. It tells me there is no schema org.mate.desktop.background.
I'd guess you copy pasted from gnome ;) Maybe it should be org.mate.background.

But apart from that it looks good now

**Comment by onli** [comment]
Thanks :) Yes, I copied that badly. `org.mate.background picture-options "stretched"` worked?

**Comment by Sh4kE** [comment]
Yes awesome :D 

Now I only need to find out how to shift the weather icons up. They are currently behind my bar. But that's not anymore case of this ticket

**Comment by onli** [comment]
Thank you for your testing!

> Now I only need to find out how to shift the weather icons up.

Right, not part of that ticket. Pointer anyway: `--compat unity`. If that does not work feel free to open a new ticket to add a new compat setting for mate.
